### ISSUE TITLE
[TWW] Prat-3.0-3.9.55/modules/PlayerNames.lua:1366: attempt to index local 'Name' (a nil value)

### ISSUE THREAD

**Issue by Sluimerstand** [Legacy-of-Sylvanaar/prat-3-0#191] opened 2024-07-24 20:19 UTC
10x Prat-3.0-3.9.55/modules/PlayerNames.lua:1366: attempt to index local 'Name' (a nil value)
[string "@Prat-3.0-3.9.55/modules/PlayerNames.lua"]:1366: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@TomTom/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceTomTom/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 modules = <table> {
 }
 Classes = <table> {
 }
 defaultModuleState = true
 Subgroups = <table> {
 }
 hooks = <table> {
 }
 db = <table> {
 }
 enabledState = true
 PL = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 pluginopts = <table> {
 }
 NEEDS_INIT = true
 baseName = "Prat-3.0"
 name = "Prat_PlayerNames"
 orderedModules = <table> {
 }
 Levels = <table> {
 }
 moduleName = "PlayerNames"
}
Name = nil
Class = nil
Level = nil
_ = nil
(for index) = 1
(for limit) = 65
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Name' (a nil value)"

**Version Information (please complete the following information):**
 - Wow Version: 110000
 - Prat Version: 3.9.55

**Addons you are running**
BugSack, BugGrabber, Simple Addon Manager, Prat 3.0

**Comment by Ookami313** [comment] 2024-07-25 03:03
Looks like the issue may be with Here Be Dragons. I replaced the libs folder with the newest 2.14.3 version and the error no longer occurs.

**Comment by Thex-PiedDroit** [comment] 2024-07-25 12:47
Got the same error; seems like Prat is trying to access the wrong Ace3 lib. For me it's getting the one from BeQuiet instead of AllTheThings (as seen in this report), but the error is the same

**Comment by KyrosKrane** [comment] 2024-07-25 15:03
The Ace3 lib has nothing to do with it. The root cause is that Prat is calling [`C_GuildInfo.GuildRoster`](https://warcraft.wiki.gg/wiki/API_C_GuildInfo.GuildRoster) then immediately trying to read guild info. However, that call is asynchronous, and the guild roster info won't actually be available until the event [`GUILD_ROSTER_UPDATE`](https://warcraft.wiki.gg/wiki/GUILD_ROSTER_UPDATE) fires. Prat should wait for that event, then once that event fires, the rest of the code can continue.

**Comment by Veyska** [comment] 2024-07-27 02:29
An additional probably relevant data point!  I just started getting this error on my most recent log-in into game and the only thing that changed was my main's guild got its first cross-realm/non-merged-realm member.  Not abusing my officer abilities to boot them back out to test though.  😅

A slightly "tidier" version of the error message, without Github eating the angle bracket-y bits (I have Ace3 installed on its own, had issues in the past with out-of-date embeds getting snippy in the past and said heckit)...
```
5x Prat-3.0-3.9.55/modules/PlayerNames.lua:1366: attempt to index local 'Name' (a nil value)
[string "@Prat-3.0-3.9.55/modules/PlayerNames.lua"]:1366: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 modules = <table> {
 }
 Classes = <table> {
 }
 defaultModuleState = true
 Subgroups = <table> {
 }
 hooks = <table> {
 }
 db = <table> {
 }
 enabledState = true
 PL = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 pluginopts = <table> {
 }
 baseName = "Prat-3.0"
 name = "Prat_PlayerNames"
 orderedModules = <table> {
 }
 Levels = <table> {
 }
 moduleName = "PlayerNames"
}
Name = nil
Class = nil
Level = nil
_ = nil
(for index) = 1
(for limit) = 512
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Name' (a nil value)"
```

**Comment by glassleo** [comment] 2024-07-28 03:04
Also getting this constantly

**Comment by jazz836062** [comment] 2024-07-28 20:18
In modules/PlayerNames.lua, change line 1363 to the following.

for i = 1, select(1,GetNumGuildMembers()) do

**Comment by zeenk** [comment] 2024-07-28 20:31
> In modules/PlayerNames.lua, change line 1363 to the following.
> 
> for i = 1, select(1,GetNumGuildMembers()) do

Doesn't work :/ you still get the same error when you login

**Comment by jazz836062** [comment] 2024-07-29 13:16
Strange that it is only on login.  Reloading doesn't experience the same issue.

**Comment by Andf** [comment] 2024-07-29 16:34
Having a very similar issue, if not the same but only on one character, my pally retri, since latest patch.

2x Prat-3.0-3.9.55/modules/PlayerNames.lua:1366: attempt to index local 'Name' (a nil value)
[string "@Prat-3.0-3.9.55/modules/PlayerNames.lua"]:1366: in function `?'
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bartender4/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 modules = <table> {
 }
 Classes = <table> {
 }
 defaultModuleState = true
 Subgroups = <table> {
 }
 hooks = <table> {
 }
 db = <table> {
 }
 enabledState = true
 PL = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 pluginopts = <table> {
 }
 NEEDS_INIT = true
 baseName = "Prat-3.0"
 name = "Prat_PlayerNames"
 orderedModules = <table> {
 }
 Levels = <table> {
 }
 moduleName = "PlayerNames"
}
Name = nil
Class = nil
Level = nil
_ = nil
(for index) = 1
(for limit) = 117
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Name' (a nil value)"

**Closed** 2024-08-02 08:38 UTC
Labels: bug, retail
