### ISSUE TITLE
Bugs report 3 May 2023 patch 10.1

### ISSUE THREAD

**Issue by Rezy942** [Legacy-of-Sylvanaar/prat-3-0#131] opened 2023-05-03 14:57 UTC
Bug #1 (present for years now):
Your main tab sometimes appears even if using the fading option on tabs.
Not sure how - but this bug has been present for many years now.
![image](https://user-images.githubusercontent.com/122007087/235954500-3a3ba6cd-5ea6-463f-a0c3-91121ecd2cf2.png)
All tabs are hidden, but the main tab remains visible, until you hover over again to "reset" the fade, after which this tab disappears again.

Bug #2 (as of patch 10.1):
Similar to 1st bug, scroll bar sometimes does not fade.
Reproduce: Set EVERYTHING in prat to fade.
Hover over the chat to "fade-in" everything.
/reload right away.
After game loads, you will see the scroll bar persist without fading.
![image](https://user-images.githubusercontent.com/122007087/235955335-f0031ccc-10f2-4bc9-8d85-65556aac850e.png)

Hopefully you can do something because the fading feature is unfortunately very buggy :(
Love the addon, thank you!!

**Comment by Rezy942** [comment] 2023-05-04 23:26
Both of these bugs are a deal breaker for me as for years i dont see any fix for #1.
Hopefully it comes one day.

**Comment by plusmouse** [comment] 2023-05-10 09:55
1. I can't reproduce it, and given the multiple reports its real, but without steps to reproduce it I can't test any fixes.

2. Fixed in the latest alphas

**Comment by Rezy942** [comment] 2023-05-10 11:57
> 1. I can't reproduce it, and given the multiple reports its real, but without steps to reproduce it I can't test any fixes.
> 
>     2. Fixed in the latest alphas

Thats unfortunate, because I stumble upon it literally 3-5 times a day even with 0 addons installed. Are you using prat with transparency set to 0? Maybe that will help recreate it?

Ive tried so many other chat addons, and none of them have this issue, so it's weird. I really love Prat but it ruins the minimalist UI look so at that point I just switch to worse alternatives that dont have this issue.

I will try to find a way to re-create this issue, but tbh setting it to 0% transparency and enabling option to hide all tabs should easily recreate it as you play the game. Im surprised you didnt notice it by now tbh, making me believe you have some setting on that prevents this from happening.



Thanks for #2!!!

**Comment by Rezy942** [comment] 2023-05-14 18:08
BasicChatMods does tab fading perfectly, in case it helps you compare the code in some way. Their tabs fade instantly and never come back after reloads.

**Comment by plusmouse** [comment] 2023-05-16 10:50
I'm going to close this issue and move the discussion to https://github.com/Legacy-of-Sylvanaar/prat-3-0/issues/74 - can you respond to the latest question there?

**Closed by plusmouse** 2023-05-16 10:50 UTC
Labels: bug, retail
