### ISSUE TITLE
new tab windo not keeping one chat ype

### ISSUE THREAD

**Issue by Tavinn** [Legacy-of-Sylvanaar/prat-3-0#176] opened 2024-03-20 03:55 UTC
**Describe the bug**
I have guild chat in a different tab so it not in the same window as trade chat , raid, chat or party chat
while it works when I'm logged in, if I log out the chat window go back to the default of all chat in both windows

**To Reproduce**
1. log in to wow and move guild chat to a different window 
2. log out on the same character 
3. now you have two chat windows with the second not filtering guild chat only

**Expected behavior**
normal these tab stay separate and the guild tab will only have guild chat in it

**Screenshots**
![normal](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/14834670/f9945407-33cd-4566-9204-c875f7264048)
![after logging out](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/14834670/63dd7ea7-f926-415d-9825-5d0bd8d65ff2)

**Version Information (please complete the following information):**
 - Wow Version:  Retail 
 - Prat Version: 3.0-3.9.47`

**Comment by chasaya** [comment] 2024-03-20 10:38
Came here to see if this is already reported, however, it is not a bug within Prat apparently, but something broken for the chat in general by the latest patch. 
Even with all addons disabled, every relog and even reload brings back all chat channels enabled in ALL chat tabs. Even with newly created windows, after a reload all standard channels are enabled. 
See here also: [https://us.forums.blizzard.com/en/wow/t/all-chat-channels-re-enabled-every-time-i-log-in/1810486](https://us.forums.blizzard.com/en/wow/t/all-chat-channels-re-enabled-every-time-i-log-in/1810486)

So, seems we'll have to wait for Blizz to fix this seizure-inducing issue unfortunately. I'd suggest reporting it ingame as a bug to put some urgency behind it.

**Comment by plusmouse** [comment] 2024-03-26 21:55
This has been fixed by Blizzard now.

**Closed by plusmouse** 2024-03-26 21:55 UTC
Labels: bug, retail
