### ISSUE TITLE
Prat keeps creating a specific chat window on all toons

### ISSUE THREAD

**Issue by Zasz333** [Legacy-of-Sylvanaar/prat-3-0#138] opened 2023-06-28 23:46 UTC
I created a new toon, a shaman, played it to 30 now. I created another window like I have on other toons for loot so it doesnt spam my regular chat window. I also have only one prat profile for all toons because so far its been the easiest way to handle my chat.

Initially when I created the new window it didnt show up. Reloaded the interface, still not there. I created another and that one finally showed up. Not sure if that is relevant because its unexpected behavior.

After leveling 10 levels, doing a few rounds on the feast with a couple of toons, suddenly prat keeps creating a chat window usually labeled "chat 5" on every toon, starting on the little shaman. Except for the new shaman. There the channel always has the name I gave it. On all other toons its called "chat 5". It always comes back at the same location. The channel doesnt show up in tab settings of prat either.

I deleted the addon settings folder for that toon but nothing changed. The window still keeps returning when I log back into any toon with prat enabled.

I removed prat completely and the window disappeared. I put prat back in, deleted the settings folder for that toon, deleted cache folder, window is back again.

I tried the memory module from a lvl70 toon but it still keeps recreating that window on every toon.

Logged onto a lvl70 toon, found the window there as expected, closed it, reloaded interface, window is there again. Same spot, same name. Chat 5.

I think this solved my problem.
I noticed it was detached from the default chat and the loot window I created a long time ago. So I merged it with the default chat/combatlog. Suddenly the window appeared in prats tab settings. So I disabled it so the tab wouldnt show up. I checked other toons and the window isnt there anymore. Just the channels Ive set up.

I dont understand exactly what happened but its solved. For now. I hope someone can make sense of it and maybe figure out which part of prat screwed up.

**Comment by Squiss2023** [comment] 2023-07-04 07:06
Ive got the same issue. Im playing on WotLK servers. 
It creates two new tabs: "Chat 4" and "Chat 5" and even if I close then, they keep getting recreated.

**Comment by plusmouse** [comment] 2023-07-04 08:09
Does the issue persist if you open the memory module settings and save them again after closing the tabs?

**Comment by Zasz333** [comment] 2023-07-04 11:25
I think I did exactly that which is why I disabled the memory module because it didnt save my settings as expected when I switched toons.

**Comment by Squiss2023** [comment] 2023-07-04 12:12
> Does the issue persist if you open the memory module settings and save them again after closing the tabs?

So I tried:
1- closed both chat windows (chat 4 & chat 5)
2- open prat panel > Extra Stuff > Memory > Save Settings.
3- logout, login again
4- both windows are shown again.

I also tried to disable the module, close the tabs and logout/login, same thing.

![Skype_Picture_2023_06_27T17_58_02_263Z](https://github.com/Legacy-of-Sylvanaar/prat-3-0/assets/138563138/6ec3aca6-19d6-4329-9167-b270a4bff6ca)

**Comment by Zasz333** [comment] 2023-07-04 16:29
Try my solution. Move the annoying tabs and merge them with the general/combat log window. Now they should be visible in the "tabs" settings" and you can remove the checks. They should be invisible now.

**Comment by Squiss2023** [comment] 2023-07-04 17:11
> Try my solution. Move the annoying tabs and merge them with the general/combat log window. Now they should be visible in the "tabs" settings" in Prat and you can remove the checks. They should be invisible now.

That indeed seems to solve the issue. Thanks :)

**Comment by Crusherix** [comment] 2023-08-14 21:18
> Try my solution. Move the annoying tabs and merge them with the general/combat log window. Now they should be visible in the "tabs" settings" in Prat and you can remove the checks. They should be invisible now.

Thank you... i were going a bit mad.
I was in the middle of troubleshooting this "Chat5" issue which only appeared with Prat enabled.
For me personally i also had a old chat tab i removed aftering going from 3 to 2 chat tabs that after some update started appearing and refusing to die, your method of docking it to main tab and then closing it works out and doesn't re-appear again however i have to do this on every single character, the memory module does not remember me docking it and closing it(yes i saved, 3 times with 5s inbetween to be sure).

Aswell, not sure why but running without prat i can clean out the "chat-cache.txt" and it stays cleaned through login/logout/restarts but with prat enabled again it fills up the file again. To clarify without prat i delete everything after "Window 4" but prat always re-add windows 5, 6, 7, 8, 9 and 10. These are not visible in-game except for window 5 which is the "Chat5" window that always showed up but can be finally killed off by docking to main window before closing as described by @Zasz333.

To current authors: Thank you for keeping this gem of an addon alive :)

**Comment by plusmouse** [comment] 2023-08-15 08:29
Thanks for the feedback. I've finally replicated the error. It is caused by the ChatTabs module. Applied a fix to the latest alpha (pending testing, then wider release)

**Closed** 2023-08-15 08:28 UTC
Labels: bug, retail

**Comment by plusmouse** [comment] 2023-08-15 08:59
[Prat-3.0-3.9.32-2-g7f1981c.zip](https://github.com/Legacy-of-Sylvanaar/prat-3-0/files/12342650/Prat-3.0-3.9.32-2-g7f1981c.zip)
